trigger:
  branches:
    include:
      - master 

pool:
  vmImage: 'windows-latest' 

variables:
  buildConfiguration: 'Release'
  solution: '**/WebApplication1.sln'
  project: 'WebApplication1/WebApplication1.csproj'
  azureWebAppName: 'webapplication120251003180125-f9c5a0ckbkdtezgw' 
  azureSubscription: 'Your-Service-Connection-Name'

steps:

# 1. Checkout source code
- task: Checkout@1

# 2. Install .NET SDK
- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '9.0.x'

# 3. Restore NuGet packages
- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet packages'
  inputs:
    command: 'restore'
    projects: '$(solution)'

# 4. Build the solution
- task: DotNetCoreCLI@2
  displayName: 'Build solution'
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'

# 5. Run tests
- task: DotNetCoreCLI@2
  displayName: 'Run unit tests'
  inputs:
    command: 'test'
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --no-build'

# 6. Publish project
- task: DotNetCoreCLI@2
  displayName: 'Publish project'
  inputs:
    command: 'publish'
    projects: '$(project)'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

# 7. Deploy to Azure Web App
- task: AzureWebApp@1
  displayName: 'Deploy to Azure Web App'
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'webApp'
    appName: '$(azureWebAppName)'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
